# -*- coding: utf-8 -*-
"""Phishing URL detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRxw293DspjyccWPqyUa3eBA7XGGZ3wr
"""

!pip install streamlit pyngrok -q

import pandas as pd
import numpy as np
import re
import pickle

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
file_path = '/content/phishing dataset.xlsx'

df = pd.read_excel(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)


print(df['class'].value_counts())
print("Phishing:", (df['class'] == 1).sum())
print("Legitimate:", (df['class'] == -1).sum())

features = ['UsingIP', 'LongURL', 'ShortURL', 'HTTPS']

X = df[features]
y = df['class']

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

lr_model = LogisticRegression()

lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

lr_accuracy = accuracy_score(y_test, lr_pred)

print("\nLogistic Regression Accuracy:",
      lr_accuracy)

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:",
      rf_accuracy)

print("Model Comparison")
print("-------------------------")

print("Logistic Regression:",
      round(lr_accuracy * 100, 2), "%")

print("Random Forest:",
      round(rf_accuracy * 100, 2), "%")

print("Random Forest Classification Report/n")


print(classification_report(
    y_test,
    rf_pred,
    target_names=['Legitimate', 'Phishing']
))

cm = confusion_matrix(y_test, rf_pred)

print("Confusion Matrix:/n")
print(cm)

sample_url = pd.DataFrame({
    'UsingIP': [0],
    'LongURL': [1],
    'ShortURL': [0],
    'HTTPS': [1]
})


model_path = '/content/rf_model.pkl'

with open(model_path, 'wb') as file:
    pickle.dump(rf_model, file)

print("Model saved successfully!")
print(model_path)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pickle
# import re
# import pandas as pd
# 
# 
# # Load trained model
# with open('rf_model.pkl', 'rb') as file:
#     model = pickle.load(file)
# 
# 
# # Feature extraction function
# def extract_features(url):
# 
#     # 1. UsingIP
#     ip_pattern = r'(\d{1,3}\.){3}\d{1,3}'
# 
#     if re.search(ip_pattern, url):
#         using_ip = 1
#     else:
#         using_ip = 0
# 
#     # 2. LongURL
#     if len(url) > 75:
#         long_url = 1
#     else:
#         long_url = 0
# 
#     # 3. ShortURL
#     short_domains = ['bit.ly', 'tinyurl', 't.co']
# 
#     if any(domain in url.lower() for domain in short_domains):
#         short_url = 1
#     else:
#         short_url = 0
# 
#     # 4. HTTPS
#     if url.lower().startswith('https://'):
#         https = 1
#     else:
#         https = 0
# 
#     return [
#         using_ip,
#         long_url,
#         short_url,
#         https
#     ]
# 
# 
# # Streamlit UI
# 
# st.set_page_config(
#     page_title="Phishing URL Detection",
#     page_icon="🔐"
# )
# 
# st.title("🔐 Phishing URL Detection")
# 
# st.write(
#     "Enter a URL below to check whether it is "
#     "Phishing or Legitimate."
# )
# 
# url = st.text_input(
#     "Enter URL",
#     placeholder="https://example.com"
# )
# 
# if st.button("Check URL"):
# 
#     if url.strip() == "":
#         st.warning("Please enter a URL.")
# 
#     else:
# 
#         # Extract features
#         features = extract_features(url)
# 
#         # Convert to DataFrame
#         input_data = pd.DataFrame(
#             [features],
#             columns=[
#                 'UsingIP',
#                 'LongURL',
#                 'ShortURL',
#                 'HTTPS'
#             ]
#         )
# 
#         # Prediction
#         prediction = model.predict(input_data)[0]
# 
#         # Phishing probability
#         probability = model.predict_proba(input_data)[0][1]
#         phishing_probability = probability * 100
# 
#         # -------------------------
#         # Final Prediction
#         # -------------------------
# 
#         if prediction == 1:
#             st.error("⚠️ Phishing URL Detected")
#         else:
#             st.success("✅ Legitimate URL")

from pyngrok import ngrok

!ngrok config add-authtoken "3JSe11eGP7PHV0AEwjLV03d0PAh_3nAAWjYngEUhazCCb7VTS"

!pkill -f streamlit

!streamlit run /content/app.py --server.port 8501 > /content/streamlit.log 2>&1 &

from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8501)

print("OPEN THIS LINK:")
print(public_url)