# -*- coding: utf-8 -*-
"""python project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXeTTw8_i_TX66j7hSR7wMrOpd2AGNGy
"""

import re
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def url_features(url):
    shorteners = ["bit.ly", "goo.gl", "tinyurl.com", "ow.ly", "t.co"]
    using_ip = -1 if re.search(r'(\d{1,3}\.){3}\d{1,3}', url) else 1

    n = len(url)
    if n < 54:       long_url = 1
    elif n <= 75:    long_url = 0
    else:            long_url = -1

    short_url = -1 if any(s in url for s in shorteners) else 1
    https = 1 if url.lower().startswith("https") else -1

    return {"UsingIP": using_ip, "LongURL": long_url,
            "ShortURL": short_url, "HTTPS": https}

df = pd.read_csv("/content/phishing.csv")
print(df.columns) # Added to inspect columns
if "Index" in df.columns:
    df = df.drop(columns=["Index"])

features = ["UsingIP", "LongURL", "ShortURL", "HTTPS"]
X = df[features]
y = df["class"].astype(int)         # 1 phishing, -1 legit

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(Xtr, ytr)
print("Test accuracy:", accuracy_score(yte, model.predict(Xte)))

# --- User URL input loop ---
while True:
    u = input("\nEnter URL (or 'exit'): ").strip()
    if u.lower() == "exit":
        break
    if not u:
        print("Please enter a URL.")
        continue

    f = url_features(u)
    x1 = pd.DataFrame([f])[features]
    pred = model.predict(x1)[0]

    print("Features:", f)
    print("Prediction:", "LEGITIMATE" if pred == 1 else "PHISHING")